# Generated by Django 3.0.7 on 2020-06-30 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ucbenik', '0004_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterDataMen',
            fields=[
                ('neck', models.CharField(max_length=30)),
                ('body_color', models.CharField(max_length=30)),
                ('height', models.CharField(max_length=5)),
                ('body_type', models.CharField(max_length=4)),
                ('hair_color', models.CharField(max_length=30)),
                ('glasses', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('beard', models.CharField(max_length=30)),
                ('suite_color', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterDataWomen',
            fields=[
                ('neck', models.CharField(max_length=30)),
                ('body_color', models.CharField(max_length=30)),
                ('height', models.CharField(max_length=5)),
                ('body_type', models.CharField(max_length=4)),
                ('hair_color', models.CharField(max_length=30)),
                ('glasses', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pants_color', models.CharField(blank=True, max_length=10)),
                ('dress_color', models.CharField(blank=True, max_length=30)),
                ('shoes_color', models.CharField(blank=True, max_length=30)),
                ('shirt_color', models.CharField(blank=True, max_length=30)),
                ('wearing', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
