# Generated by Django 3.0.7 on 2020-07-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucbenik', '0007_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_page',
            field=models.CharField(default='', max_length=30),
        ),
    ]
