# Generated by Django 3.0.7 on 2020-07-29 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ucbenik', '0009_excersise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Excersise',
            new_name='Exercise',
        ),
    ]
