# Generated by Django 3.0.7 on 2020-07-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ucbenik', '0010_auto_20200729_1741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercise',
            new_name='Solution',
        ),
    ]
