# Generated by Django 3.0.7 on 2020-08-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucbenik', '0011_auto_20200729_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chapters',
            field=models.CharField(default='Introduction', max_length=200),
        ),
    ]
