# Generated by Django 3.2 on 2021-04-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucbenik', '0012_user_chapters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
